// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDipTnvA6xYCQJfG_ZuOhZ1-E_P22-CJ3o',
    appId: '1:564429790459:web:11b03fb4fbd35cf573245e',
    messagingSenderId: '564429790459',
    projectId: 'barrera-cero-e162f',
    authDomain: 'barrera-cero-e162f.firebaseapp.com',
    storageBucket: 'barrera-cero-e162f.firebasestorage.app',
    measurementId: 'G-KTH1CXF0DV',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD-6d5U9RCRFKEqVVAJAesVA8loMzzA6b4',
    appId: '1:564429790459:android:8b63b03a12936e2273245e',
    messagingSenderId: '564429790459',
    projectId: 'barrera-cero-e162f',
    storageBucket: 'barrera-cero-e162f.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCMQTznAEy2W_bh-cCR6GlJQIlrG_wmSgc',
    appId: '1:564429790459:ios:5bbe655d1e11482373245e',
    messagingSenderId: '564429790459',
    projectId: 'barrera-cero-e162f',
    storageBucket: 'barrera-cero-e162f.firebasestorage.app',
    iosBundleId: 'com.example.barreracero',
  );
}
